
;

#global testerror;
func main ()
{
	return 1;
}
