#global testerror "Err0081"
func(op: string) toto() {}

#test
{
    toto()
}
