#global testerror "Err0604"
func arithmeticMean(numbers: f32...) {}

#test
{
    arithmeticMean(true, 2)
}
