
#global testerror "Err0649"
func arithmeticMean(numbers: f32...)
{
}

#test
{
    arithmeticMean(true, 2)
}
