#global testerror "Err0428"

#test
{
    loop a in {}
}