#global testerror "Err0648"
#test
{
    let a = 5 + {2}
}