#global testerror "Err0681"
func toto() throw
{
    throw A{}
}